version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
    ports:
      - "33066:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
